version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "33020:3306"
